# Generated by Django 5.0.6 on 2026-05-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='commande',
            name='heure_retrait',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de passage prévue'),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(choices=[('livraison', 'Livraison à domicile'), ('retrait', 'Retrait en magasin')], default='livraison', max_length=20, verbose_name='Mode de récupération'),
        ),
        migrations.AddField(
            model_name='commande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('prete', 'Prête / En livraison'), ('livree', 'Livrée / Récupérée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
