# Generated by Django 5.0.6 on 2026-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Format international, ex : +213 6XX XXX XXX', max_length=30, verbose_name='Numéro WhatsApp')),
                ('whatsapp_apikey', models.CharField(blank=True, help_text='Obtenez-la sur callmebot.com', max_length=50, verbose_name='Clé API CallMeBot')),
                ('actif', models.BooleanField(default=True, verbose_name='Notifications actives')),
            ],
            options={
                'verbose_name': 'Configuration WhatsApp',
                'verbose_name_plural': 'Configuration WhatsApp',
            },
        ),
    ]
