# Generated by Django 5.0.6 on 2026-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Badge (ex : Nouveau, Promo)')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Image (1400×600 recommandé)')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='Lien (URL ou chemin)')),
                ('lien_texte', models.CharField(blank=True, default='Découvrir', max_length=60, verbose_name='Texte du bouton')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide carousel',
                'verbose_name_plural': 'Slides carousel',
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
