# Generated by Django 5.2.15 on 2026-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nom_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='badge_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge (ex : Nouveau, Promo)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='badge_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge (ex : Nouveau, Promo)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='badge_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge (ex : Nouveau, Promo)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='lien_texte_ar',
            field=models.CharField(blank=True, default='Découvrir', max_length=60, null=True, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='lien_texte_en',
            field=models.CharField(blank=True, default='Découvrir', max_length=60, null=True, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='lien_texte_fr',
            field=models.CharField(blank=True, default='Découvrir', max_length=60, null=True, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='sous_titre_ar',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='sous_titre_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='sous_titre_fr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='titre_ar',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='titre_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='titre_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
    ]
